Add support for read-only /boot/efi
This is needed on the Framework laptop.

diff --git a/remount-boot-ro b/remount-boot-ro
--- a/remount-boot-ro
+++ b/remount-boot-ro
@@ -1,8 +1,13 @@
 #!/bin/bash
 
-rm -f /var/lock/partition-boot /var/lock/partition-boot.remount-boot-rw
+rm -f /var/lock/partition-boot /var/lock/partition-boot.remount-rw
 echo "Remounting /boot as ro after dpkg run"
 if ! mount -o remount,ro /boot ; then
     echo "Cannot re-mount /boot ro"
-    exit 1
+fi
+
+rm -f /var/lock/partition-boot-efi /var/lock/partition-boot-efi.remount-rw
+echo "Remounting /boot/efi as ro after dpkg run"
+if ! mount -o remount,ro /boot/efi ; then
+    echo "Cannot re-mount /boot/efi ro"
 fi
diff --git a/remount-boot-rw b/remount-boot-rw
--- a/remount-boot-rw
+++ b/remount-boot-rw
@@ -2,9 +2,18 @@
 
 if lockfile -r 8 /var/lock/partition-boot ; then
     echo "Remounting /boot as rw before dpkg run"
-    touch /var/lock/partition-boot.remount-boot-rw
+    touch /var/lock/partition-boot.remount-rw
     mount -o remount,rw /boot
 else
     echo "Cannot re-mount /boot rw"
+    exit 1
+fi
+
+if lockfile -r 8 /var/lock/partition-boot-efi ; then
+    echo "Remounting /boot/efi as rw before dpkg run"
+    touch /var/lock/partition-boot-efi.remount-rw
+    mount -o remount,rw /boot/efi
+else
+    echo "Cannot re-mount /boot/efi rw"
     exit 1
 fi
